[package]
edition = "2021"
name = "srf05-imu-station"
version = "0.1.0"
license = "MIT or Apache-2.0"

[dependencies]
srf05 = { path = "../crates/srf05" }
motion-core = { path = "../crates/motion-core" }
cortex-m = "0.7.9"
cortex-m-rt = "0.7"
embedded-hal = { version = "1.0.0" }
rp2040-hal = { version = "0.12.0", features = ["rt", "critical-section-impl"] }
embedded-io = "0.7"
heapless = "0.9.3"
embedded-hal-bus = "0.3.0"

defmt = "1.1.1"
defmt-serial = "0.14.0"
usb-device = "0.3"
usbd-serial = "0.2"

panic-persist = { version = "0.3", features = ["utf8"] }
rp2040-boot2 = "0.3.0"
critical-section = "1.2.0"
static_cell = "2.1.1"
portable-atomic = { version = "1", default-features = false, features = [
    "critical-section",
] }
embedded-graphics = "0.8.2"
ssd1306 = "0.10.0"

panic-halt = "1.0.0"

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3

#remove auto-test for ide
[[bin]]
name = "srf05-imu-station"
path = "src/main.rs"
test = false
bench = false
